properties:
  - id: 1
    name: Comfort Inn Beckley
    address: 300 Harper Park Dr, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    is_mine: true
    brand: choice        # ⬅️ NEW

  - id: 2
    name: Courtyard Beckley
    address: 124 Old Beckley Crossing, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: marriott

  - id: 3
    name: Hampton Inn Beckley
    address: 110 Harper Park Dr, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: hilton

  - id: 4
    name: Tru by Hilton Beckley
    address: 162 Harper Park Dr, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: hilton

  - id: 5
    name: Fairfield Inn Beckley
    address: 83 Centre Dr, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: marriott

  - id: 6
    name: Best Western Beckley
    address: 125 Hylton Ln, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: bestwestern

  - id: 7
    name: Country Inn Beckley
    address: 2120 Harper Rd, Beckley, WV 25801
    city: Beckley
    state: WV
    timezone: America/New_York
    brand: radisson   # (Country Inn & Suites)
