name: nightly
on:
  schedule:
    - cron: "7 4 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      # Install Playwright browser deps (safe even if you don't use brand fetch yet)
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run jobs (generate JSON)
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python -m app.run_jobs

      - name: Commit data
        run: |
          git config user.name "RateBot"
          git config user.email "ratebot@users.noreply.github.com"
          git add data/
          git commit -m "data: nightly $(date -u +%F)" || echo "no changes"
          git push
